ConduitIO/conduit-connector-postgres

- README.md
1. Updates documentation about operation mode (cdc, snapshot)
2. Removes unused `replication_url` parameter.
> Update documentation about mode, remove unused param

- README.md
- source/config.go
- source/config_test.go
- source/longpoll/snapshot.go
- source/longpoll/snapshot_test.go
- source/source.go
This change removes the `mode` option and instead introduces two options:
- `snapshot_mode` - can be used to turn snapshot on/off, right now two options are supported: `initial` (default) enables the snapshot at the start, `never` turns the snapshot off.
- `cdc_mode` - can be used to pick the mode of detecting CDC changes, right now three options are supported: `auto` (default) detects if logical replication is supported and falls back to long polling if it's not, `logrepl` forces logical replication, `long_polling` forces long polling.
This PR also fixes the long polling snapshot iterator by removing `HasNext`, since the source doesn't call that method.
Based on #11.
> Config options "cdc_mode" and "snapshot_mode"

- destination/destination.go
- destination/destination_test.go
Adds delete handling to the destination connector.
> adds delete handler to destination

- source/logrepl/internal/relationset_test.go
This changes `TestRelationSetAllTypes` so it is allowed to catch any number of empty transactions before getting to the one it actually expects.
Fixes #37
> Fix TestRelationSetAllTypes

- README.md
Removes references to the unimplemented long polling `cdcMode` from the README.
Fixes # (issue)
> fix: remove reference to unimplemented long polling mode

- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
- .golangci.yml
- go.mod
> Upgrade to Go 1.20, remove abandoned linters

- destination/destination.go
- destination/destination_test.go
- go.mod
- go.sum
This PR changes the behavior for batching so that the queries for all records in a batch are sent to Postgres in one round-trip. This significantly increases performance when batching is enabled - in my tests I achieved 15k msg/s instead of previously 800.
It also updates the SDK dependency to enable the batching middleware. Before releasing the connector we should update the dependency to a proper semver version.
> Enable batching in destination

- README.md
- source.go
- source/config.go
- source/config_test.go
- source/logrepl/cdc.go
- source/logrepl/cdc_test.go
- source/logrepl/handler.go
- source/logrepl/internal/subscription.go
- source/longpoll/snapshot.go
- source/paramgen.go
support reading from multiple tables using logical replication slots.
changes to params:
* "columns" param is removed.
* "key" param is updates now to accept multiple tables and keys, as a list of pairs, example: "table1:key1,table2:key2", if the key is not provided, we'll fetch the table's primary key.
Fixes #23
> support reading from multiple tables using logical replication slots

- README.md
Clarifies the documentation around the `table` field in a destination configuration.
> Clarify destination connector config for table

- source.go
- source_integration_test.go
13d4cad refactored Configure(), but in the process failed to initialize the tableKeys field, which ends up panic()ing due to an uninitialized map when scanning the table primary keys.
This commit fixes this. :)
Please include a summary of the change and what type of change it is (new feature, bug fix, refactoring, documentation).
Please also include relevant motivation and context.
List any dependencies that are required for this change.
Fixes # (issue)
> Add missing initialization for tableKeys field

- source.go
- source/config.go
- source/logrepl/combined.go
- source/paramgen.go
- source/snapshot/fetch_worker.go
- source/snapshot/iterator.go
Add config for snapshot fetch size.
> Ensure defaults for publication, slot, auto-cleanup are available to lifecycle events.

- Makefile
- source/logrepl/cdc_test.go
- source/logrepl/combined_test.go
- source/logrepl/handler.go
- source/logrepl/internal/subscription.go
- source/logrepl/internal/subscription_test.go
* Ensure expected commit lsn matches that of begin messages.
* Adjust the status update to send the last server lsn when all data nas been written and acked. This change will help with managing server lag with relatively less frequently updated tables.
> Improve handling of keepalive messages and manage server end lag.

- source/logrepl/cdc.go
- source/snapshot/fetch_worker.go
> add extra log metrics for snapshot progress

- source.go
- source/cpool/cpool.go
- source/logrepl/cdc.go
- source/logrepl/cdc_test.go
- source/logrepl/cleaner.go
- source/logrepl/combined.go
- source/logrepl/combined_test.go
- source/logrepl/internal/publication.go
- source/logrepl/internal/publication_test.go
- source/logrepl/internal/relationset_test.go
- source/logrepl/internal/replication_slot.go
- source/logrepl/internal/replication_slot_test.go
- source/logrepl/internal/subscription.go
- source/logrepl/internal/subscription_test.go
- source/pool/pool.go
- test/conf.d/postgresql.conf
- test/helper.go
* Read the state of the replication slot when subscription is created.
* Ensure the starting position in CDC mode is consistent with what is available in the slot.
* Refactor connection management to use pgxpool and allow for acquired connections to be upgraded for replication
* Add subscription teardown method which stops and waits for wind down.
Fixes #146
> Add support for reading replication slot

- .golangci.yml
- source/cpool/cpool.go
- source/logrepl/cleaner.go
- source/logrepl/combined_test.go
- source/logrepl/internal/subscription.go
- source/schema/avro.go
- source/schema/avro_test.go
- source/snapshot/fetch_worker.go
* Fix issues related to repl connection disconnect right after long snapshot completes.
* Fix block when replication cannot start, for any reason.
* Avro decimal fixes
Fixes #181
> Fix replication timeout right after long snapshot; avro fixes.

- source/logrepl/combined_test.go
The fetchers may not have started right after the iterator is created. Interrupt after snapshotter has started.
Fixes ![Screenshot 2024-07-18 at 17 54 43](https://github.com/user-attachments/assets/a0bf398e-3afa-49c0-b6bc-1b0e530420f4)
> Fix race in combined iterator test

- source.go
Postgres source will produce its own schema; disable autogen.
In preparation to enable schema building in Postgres
> Postgres source will produce its own schema; disable autogen

- README.md
The destination option table is missing a key field.
Fixes # (issue)
> fix: md format & destination table

- go.mod
- go.sum
- source/logrepl/internal/relationset.go
- source/types/types.go
> Upgrade pgx to 5.7.1

- source/schema/avro.go
- source/schema/avro_test.go
- test/helper.go
Since each value may have larger size, as per spec https://avro.apache.org/docs/1.10.2/spec.pdf
```json
{
"type": "bytes",
"logicalType": "decimal",
"precision": 4,
"scale": 2
}
```
> A decimal logical type annotates Avro bytes or fixed types. The byte array must contain the two's-complement representation of the unscaled integer value in big-endian byte order. The scale is fixed, and is specified using an attribute.
> Use bytes instead of [n]bytes to represent decimal type

- destination_integration_test.go
- go.mod
- source/logrepl/cdc_test.go
- source/logrepl/combined_test.go
- source/logrepl/internal/publication_test.go
- source/logrepl/internal/relationset_test.go
- source/logrepl/internal/replication_slot_test.go
- source/logrepl/internal/subscription_test.go
- source/schema/avro_test.go
- source/snapshot/fetch_worker_test.go
- source/snapshot/iterator_test.go
- source_integration_test.go
- test/helper.go
Added logs to the tests. My reason is that I want to see the behavior of the PostgreSQL snapshot so I can mimic it in my MySQL connector. I'd like to see the logs of the operation, and there's no better way than to just run the tests.
> add connector logs to tests

- source/schema/avro_test.go
Found a missing assertion in the schema tests.
> add missing assertion

- source/cpool/cpool.go
- source/cpool/json.go
- source/cpool/json_test.go
- source/logrepl/cdc_test.go
- source/logrepl/combined_test.go
- source/logrepl/internal/relationset.go
- source/logrepl/internal/relationset_test.go
- source/schema/avro.go
- source/snapshot/fetch_worker_test.go
- test/helper.go
By default pgx will use encoding/json and return a map of the json. This behaviour does not play well with Avro and can result in each record to emit different schema (since JSON can be anything).
Thus any JSON data will be returned as bytes and allow the user to serder into whatever type they desire.
Fixes #229
> Handle `json` and `jsonb` types as bytes.

- source/snapshot/iterator.go
- source/snapshot/iterator_test.go
snapshot records don't have the metadata key opencdc.collection
> add opencdc.collection metadata key for snapshots

- .golangci.yml
this field is no longer supported, and is causing problems with the linter workflow for other PRs, like this [one](https://github.com/ConduitIO/conduit-connector-postgres/pull/251).
this PR removes the `check-shadowing` proberty.
> Property 'check-shadowing' is not allowed 

- README.md
- connector.yaml
- source/config.go
- source/logrepl/internal/publication_test.go
- source_integration_test.go
In the spirit of getting familiar with the code base I added a fix with validation rules for `logrepl.slotName` config which I myself got bitten by.
Turns out, publications are fine with special characters in the name, but not replication slots.
Oddly, this is the only place where it's documented: https://www.postgresql.org/docs/17/warm-standby.html#STREAMING-REPLICATION-SLOTS-MANIPULATION
> Validate logical replication slot name

- source/logrepl/cdc.go
- source/logrepl/cdc_test.go
- source/logrepl/combined.go
- source/logrepl/combined_test.go
Something on https://github.com/ConduitIO/conduit-connector-postgres/pull/276, more particularly on [this diff](https://github.com/conduitio/conduit-connector-postgres/compare/3331840fb4fd74416a49a487eead71c37f21eae8..d61629dab4fdabda593404d72bca7d1c7b0e1fc2), made my benchmarks slower. 
i.e.: 
- commit 3331840fb4fd74416a49a487eead71c37f21eae8 was fast 
- commit d61629dab4fdabda593404d72bca7d1c7b0e1fc2 was 10x slower.
**Update**
⚠️ This fixes the issue: https://github.com/ConduitIO/conduit-connector-postgres/pull/279/commits/4abb909c15218c9f0a99a3815954d41bdac7d6bd ⚠️
> fix: speed on ReadN

- connector.yaml
- source/snapshot/iterator.go
Leftover from https://github.com/ConduitIO/conduit-connector-postgres/pull/279. Forgot the snapshot iterator:
- with `records := make([]opencdc.Record, 0, n)` => 8332.25 msg/s 
- with `var records []opencdc.Record` => 148174.05 msg/s
It prepares the connector for a newer release.
> fix snapshot allocation

- destination.go
- destination_integration_test.go
- go.mod
- internal/db_info.go
- source/logrepl/cdc_test.go
- source/logrepl/combined_test.go
- source/logrepl/internal/relationset_test.go
- source/snapshot/fetch_worker_test.go
- source/types/numeric.go
- source/types/types.go
- source/types/types_test.go
- source_integration_test.go
- test/docker-compose.yml
Closes https://github.com/ConduitIO/conduit-connector-postgres/issues/292.
This PR adds support for reading `numeric`/`decimal` values and writing those. The values are read into `big.Rat` values. `big.Rat` values are also written into `numeric`/`decimal` columns in the database.
To convert a `big.Rat` value (which is a fractional number) into a numeric value, we need to calculate the ratio up to a given precision, which is retrieved from the database. The precision/scale from the database is cached and expires after 5 minutes.
> Supporting reading and writing numeric/decimal values without loss of precision
